#! /bin/sh
source /home/nathaniel/.environment_variables

if [ "$#" -ge "2" ]; then
	NETWORK_NAME=$1
	NETWORK_PASS=$2
elif [ "$1" = "read" ]; then
	echo "Enter network name":
	read NETWORK_NAME
	echo "Enter network password (will not be saved anywhere):"
	read NETWORK_PASS
elif [ "$1" = "mellon" ]; then
	NETWORK_NAME=$NETW_MELLON
	NETWORK_PASS=$NETW_MELLON_PASS
elif [ "$1" = "norton" ]; then
	NETWORK_NAME=$NETW_NORTON
	NETWORK_PASS=$NETW_NORTON_PASS
elif [ "$1" = "artaxerxes" ]; then
	NETWORK_NAME=$NETW_ARTAXERXES
	NETWORK_PASS=$NETW_ARTAXERXES_PASS
elif [ "$1" = "churchill" ]; then
	NETWORK_NAME=$NETW_ALLRED_F
	NETWORK_PASS=$NETW_ALLRED_F_PASS
else
	echo 'matched network not found, defaulting to mellon network'
	NETWORK_NAME=$NETW_MELLON
	NETWORK_PASS=$NETW_MELLON_PASS
fi

echo "Attempting to connect to $NETWORK_NAME ..."
echo "wpa_supplicant -B -D nl80211,wext -i wlp3s0 -c <(wpa_passphrase '$NETWORK_NAME' '$NETWORK_PASS')" | bash
