c.colors.hints.bg = "qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 247, 133, 0.95), stop:1 rgba(255, 197, 66, 0.95))"
c.colors.tabs.even.bg = "grey"
c.colors.tabs.odd.bg = "grey"
c.colors.webpage.bg = "#ccc"
c.completion.delay = 200
c.completion.height = "20%"
c.content.autoplay = False
c.content.default_encoding = "utf-8"
c.content.geolocation = False
c.content.headers.user_agent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
c.content.pdfjs = False # TODO: Figures out why it isn't picking up on pdfjs
c.content.private_browsing = True
c.downloads.location.directory = "~/Downloads"
c.downloads.location.prompt = False
c.downloads.position = "bottom"
c.fonts.completion.category = "15pt monospace"
c.fonts.completion.entry = "15pt monospace"
c.fonts.hints = "bold 24pt monospace"
c.fonts.prompts = "15pt monospace"
c.fonts.statusbar = "15pt monospace"
c.fonts.tabs = "15pt monospace"
c.new_instance_open_target = "tab-bg-silent"
c.qt.highdpi = True
c.tabs.background = True
c.tabs.last_close = "close"
c.tabs.mousewheel_switching = False
c.url.default_page = "file:///home/nathaniel/.utils/blank.html"
c.url.searchengines = {"DEFAULT": "https://www.google.com/search?hl=en&q={}" }
c.url.start_pages = ["file:///home/nathaniel/.utils/blank.html"]
